### ISSUE TITLE
Questions about the blurimage

### ISSUE THREAD

**Issue by lvlingsheng** [ariok/TB_TwitterUI#5]
Hello:

I have downloaded your code, and it is great. I only have one question, can I set the blurimage with data from web?

Like:  
        backimage = UIImage(data: imageData!)
        header.insertSubview(headerImageView, belowSubview: headerLabel)
        headerBlurImageView?.image = backimage!.blurredImageWithRadius(10, iterations: 20, tintColor: UIColor.clearColor())

I have tried this, doesn't work. Is it the limit from FXBlur?

Thanks so much

**Comment by ariok** [comment]
The FXBlurView is not part of this repository... here is the repo for that class:  https://github.com/nicklockwood/FXBlurView

**Comment by ariok** [comment]
Anyway, I suppose you can get the image from wherever you prefer. Just be sure the image has been completely downloaded before setting it as content of the UIImageView.
